# Generated by Django 5.1.2 on 2026-05-10 18:13

from django.db import migrations, models


def migrate_ba_to_product_owner(apps, schema_editor):
    User = apps.get_model('infrastructure', 'User')
    User.objects.filter(role='ba').update(role='po')


def migrate_product_owner_to_ba(apps, schema_editor):
    User = apps.get_model('infrastructure', 'User')
    User.objects.filter(role='po').update(role='ba')


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructure', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(migrate_ba_to_product_owner, migrate_product_owner_to_ba),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('reporter', 'Reporter'), ('developer', 'Developer'), ('po', 'Product Owner'), ('admin', 'Admin')], default='reporter', max_length=20),
        ),
    ]
