# Generated by Django 5.1.2 on 2026-05-25 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructure', '0004_bugcommentattachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='bug',
            name='notification_email',
            field=models.EmailField(blank=True, help_text='Optional email to receive updates about this bug', max_length=254),
        ),
    ]
