# Generated by Django 5.1.2 on 2026-05-25 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructure', '0005_add_notification_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='bug',
            name='notification_emails',
            field=models.TextField(blank=True, help_text='Optional comma-separated emails to receive updates about this bug'),
        ),
    ]
