# Generated by Django 5.1.2 on 2026-05-25 21:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructure', '0006_add_notification_emails'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bugattachment',
            name='caption',
        ),
        migrations.RemoveField(
            model_name='bugcommentattachment',
            name='caption',
        ),
    ]
