# Generated by Django 5.1.2 on 2026-06-05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructure', '0007_remove_attachment_caption'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bug',
            name='notification_emails',
        ),
        migrations.AlterField(
            model_name='bug',
            name='notification_email',
            field=models.EmailField(blank=True, help_text='Optional email(s) to receive updates about this bug (comma-separated)', max_length=254),
        ),
    ]
