import os
import base64
from datetime import datetime

os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'config.settings')
from pathlib import Path
import sys
# ensure project root is on PYTHONPATH when running script from scripts/ folder
sys.path.append(str(Path(__file__).resolve().parent.parent))

import django
django.setup()

from infrastructure.models import Bug, BugAttachment, User, Company
from django.core.files.base import ContentFile
from django.utils import timezone

# pick reporter
reporter = User.objects.filter(username='reporter').first() or User.objects.first()
if not reporter:
	print('No user found; abort')
	raise SystemExit(1)

company = Company.objects.first()
if not company:
	company = Company.objects.create(name='DemoCo', slug='democo', product_name='Demo', is_active=True)

# create a bug
bug = Bug.objects.create(
	reporter=reporter,
	company=company,
	product=company.product_name,
	module='TestModule',
	title=f'Auto test bug {datetime.utcnow().isoformat()}',
	description='Generated by test script',
	reproduction_steps='',
	expected_result='',
	actual_result='',
	severity='low',
	impact=1,
	similar_count=0,
	module_importance=1,
)

# tiny 1x1 PNG
png_b64 = 'iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR4nGNgYAAAAAMAASsJTYQAAAAASUVORK5CYII='
data = base64.b64decode(png_b64)
subdir = timezone.now().strftime('bug_attachments/%Y/%m/%d')
filename = 'test_attachment.png'

attachment = BugAttachment(bug=bug, uploaded_by=reporter)
attachment.image.save(filename, ContentFile(data), save=True)

print('Created bug id=', bug.pk)
print('Attachment saved to', attachment.image.url)
